"""empty message

Revision ID: 1b633f14360a
Revises: d457ec6e7126
Create Date: 2021-02-17 13:25:24.615983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b633f14360a'
down_revision = 'd457ec6e7126'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('date_updated', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'product', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='unique')
    op.drop_column('product', 'date_updated')
    # ### end Alembic commands ###
