"""empty message

Revision ID: 575e7f3ffa65
Revises: d8d4a09d64ae
Create Date: 2021-02-15 14:02:01.203577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '575e7f3ffa65'
down_revision = 'd8d4a09d64ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
